export const INITIAL_VOTING_FORM_DETAILS = {
  voterPhoneNumber: "",
  voterAge: 18,
  voterSex: "",
  voterDistrict: "",
  voterPoliticalParty: "",
};
export const TAMILNADU_DISTRICTS = [
  "Select district",
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kancheepuram",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivagangai",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi (Tuticorin)",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
  "Kanyakumari",
];
export const ALL_TAMILNADU_DISTRICTS = [
  "All",
  "Ariyalur",
  "Chengalpattu",
  "Chennai",
  "Coimbatore",
  "Cuddalore",
  "Dharmapuri",
  "Dindigul",
  "Erode",
  "Kallakurichi",
  "Kancheepuram",
  "Karur",
  "Krishnagiri",
  "Madurai",
  "Mayiladuthurai",
  "Nagapattinam",
  "Namakkal",
  "Nilgiris",
  "Perambalur",
  "Pudukkottai",
  "Ramanathapuram",
  "Ranipet",
  "Salem",
  "Sivagangai",
  "Tenkasi",
  "Thanjavur",
  "Theni",
  "Thoothukudi (Tuticorin)",
  "Tiruchirappalli",
  "Tirunelveli",
  "Tirupathur",
  "Tiruppur",
  "Tiruvallur",
  "Tiruvannamalai",
  "Tiruvarur",
  "Vellore",
  "Viluppuram",
  "Virudhunagar",
  "Kanyakumari",
];
export const TAMILNADU_POLITICAL_PARTIES = [
  "Select political party",
  "DMK (Dravida Munnetra Kazhagam)",
  "AIADMK (All India Anna Dravida Munnetra Kazhagam)",
  "BJP (Bharatiya Janata Party)",
  "INC (Indian National Congress)",
  "PMK (Pattali Makkal Katchi)",
  "DMDK (Desiya Murpokku Dravida Kazhagam)",
  "NTK (Naam Tamilar Katchi)",
  "MNM (Makkal Needhi Maiam)",
  "TMMK (Tamil Nadu Muslim Munnetra Kazhagam)",
  "VCK (Viduthalai Chiruthaigal Katchi)",
  "CPI (Communist Party of India)",
  "CPI(M) (Communist Party of India - Marxist)",
  "AMMK (Amma Makkal Munnetra Kazhagam)",
  "TMC(M) (Tamil Maanila Congress)",
  "AIADMK (OPS / EPS factions, if split)",
  "INDEPENDANT",
  "NOTA"
];
export const INITIAL_FORM_RESULTS= {
  totalCount: 0,
  voterDistrict: "",
  voterPoliticalParty: "",
  count: 0
}
